# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "51bd268f9d9243f7b0748759d81d6b60"
name = "demo-app"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_customers,read_locales,read_orders,read_translations,write_translations,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
